# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjueCttO2RM7kJX7wsFUzb8pNDLBWr4z

**정렬 1번째 문제, K번째 수**
"""

def solution(array, commands):
    ind=[]; new_arr=[]; k_list=[];
    for ele1 in commands:
        ind = [] #command 요소 리스트 다시 초기화
        for ele2 in ele1:
            ind.append(ele2) #첫번째 command 리스트 안에 리스트 요소 추가
        new_arr = array[ind[0]-1:ind[1]] #ind 리스트의 첫번째 두 번째 숫자까지 슬라이싱(인덱스는 0부터 시작, 인덱스-1)
        k_list.append(sorted(new_arr)[ind[2]-1]) #오름차순 정렬, ind 리스트의 2번재 값(k번째)에서 -1한 값을 k_리스트에 넣기기 (인덱스가 0부터 시작해서)
    return(k_list) #반환

#실험용용
print(solution([1, 5, 2, 6, 3, 7, 4],[[2, 5, 3], [4, 4, 1], [1, 7, 3]]))

#다른 사람 풀이
# def solution(array, commands):
#     return list(map(lambda x:sorted(array[x[0]-1:x[1]])[x[2]-1], commands))

# def solution(array, commands):
#     answer = []
#     for command in commands:
#         i,j,k = command
#         answer.append(list(sorted(array[i-1:j]))[k-1])
#     return answer