# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

from collections import Counter

def solution(nums):
    first = Counter(nums) #nums에 있는 원소 세기
    type_num = len(first) #종류 구하기
    N_half = len(nums)/2
    if(N_half == type_num): #폰켓몬 종류랑 N/2랑 같으면
        return type_num
    elif(N_half > type_num):
        return type_num
    elif(N_half < type_num):
        return N_half

# 아니 난 개고생했는데 너무 편하게 풀었잖아
# def solution(ls):
#     return min(len(ls)/2, len(set(ls)))