# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(s):
  #stack 사용해야할 듯
  #리스트로만 생각했는데...
    stack = []
    for i in s:
        if i == '(':  # '('는 stack에 추가
            stack.append(i)
        else:  # i == ')'인 경우
            if stack == []:  # 괄호 짝이 ')'로 시작하면 False 반환
                return False
            else:
                stack.pop()  # '('가 ')'와 짝을 이루면 stack에서 '(' 하나 제거
    
    return stack==[]

# 이 방식대로 하려고 했음
# def is_pair(s):
#     # 함수를 완성하세요
#     open_cnt = 0
#     for c in s:
#         if c == '(':
#             open_cnt += 1
#         elif c == ')':
#             open_cnt -= 1
#             if open_cnt < 0:
#                 return False
#     return open_cnt == 0    

# def is_pair(s):
#     # 함수를 완성하세요
#     x = 0
#     for w in s:
#         if x < 0:
#             break
#         x = x+1 if w=="(" else x-1 if w==")" else x
#     return x==0

# def is_pair(s):
#     st = list()
#     for c in s:
#         if c == '(':
#             st.append(c)

#         if c == ')':
#             try:
#                 st.pop()
#             except IndexError:
#                 return False

#     return len(st) == 0