# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(n, lost, reserve):
  #여분이 있는 데 잃어버린 사람 제거
  new_lost = list(set(lost).difference(set(reserve)))
  new_reserve =list(set(reserve).difference(set(lost)))
  result=[j for i in new_lost for j in new_reserve if i-1<= j <= i+1]
  return (n if (len(set(result)) >= len(new_lost)) else n - (len(new_lost) - len(set(result))))

print(solution( 5, [4, 2], [3, 5]))
# print(solution(5,[2, 4],[3]))
# print(solution(3,[3],[1]))

#다른 사람의 풀이1.. 더 있었는데 다들 새로 추가된 테스트 케이스 실패한 듯..
# def solution(n, lost, reserve):
#     reserved = 0
#     lostN = list(set(lost) - set(reserve))
#     reserveN = list(set(reserve) - set(lost))
#     lostN.sort()
#     for l in lostN:
#         for x in range(l-1, l+2):
#             if x in reserveN:
#                 reserveN.remove(x)
#                 reserved += 1
#                 break
#     return n - len(lostN) + reserved