# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(a, b):
    a_b_list=[]
    if (a==b):
        return a
    a_b_list.extend([i for i in range(a,b+1) if (a<b)])
    a_b_list.extend([j for j in range(b,a+1) if (a>b)])
    return sum(a_b_list)

print(solution(1,5))
print(solution(3,3))
print(solution(5,3))

#문법만 알았다면.....내가 찾던 문법이 여깄네네
# def adder(a, b):
#     # 함수를 완성하세요
#     if a > b: a, b = b, a

#     return sum(range(a,b+1))

#수학적인 접근 n(n+1)/2, 시간복잡도O(1)
# def adder(a, b):
#     return (abs(a-b)+1)*(a+b)//2

#min이랑 max 쓰면면 되는 거였는데...
# def adder(a, b):
#     # 함수를 완성하세요
#     return sum(range(min(a,b),max(a,b)+1))