# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(arr):
    sum = 0.0
    for i in arr:
        sum += i
    return (sum/len(arr))
# return (sum(list) / len(list))