# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(strings, n): #람다를 쓰면 잘 될 거 같은 삘링이 와..
  #인덱스 1의 문자가 같은 문자열이 여럿 일 경우, 사전순으로 앞선 문자열이 앞쪽에 위치
  #미리 한번 정렬 필요
  strings.sort()
  return sorted(strings,key = lambda x : x[n]) 

print(solution(["sun", "bed", "car"],1)) 
print(solution(["abce", "abcd", "cdx"],2))