# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(s):
    return(s.isdecimal() if (len(s)== 4 or len(s)==6) else False)
  
print(solution("a2345aaa"))
print(solution("1234dddddd"))

#다른사람의 풀이..
#in (4,6) 활용하면 좋았을 듯
#isdigit() 문자열을 구성하는 각 문자들이 숫자여야 True
# def alpha_string46(s): 
#     return s.isdigit() and len(s) in (4, 6)