# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(t, p):
  com_t = []
  for i in range(len(t)-(len(p)-1)):
    com_t.append(t[i:i+(len(p))])
  
  new_com_t = []
  for i in com_t:
    if (int(''.join(i)) <= int(p)):
      new_com_t.append(int(''.join(i)))
  return len(new_com_t)

print(solution("3141592","271"))
print(solution("500220839878","7"))
print(solution("10203",	"15"))

#다른 사람의 풀이1.
def solution(t, p):
    answer = 0

    for i in range(len(t) - len(p) + 1):
        if int(p) >= int(t[i:i+len(p)]):
            answer += 1

    return answer