# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WM3VWkTr_hdUuxpAYUwcp_Fq_E_fh4uY
"""

def solution(arr):
     arr.remove(min(arr))
     return arr or [-1]

print(solution([4,3,2,1]))
print(solution([10]))

#다른 사람 풀이 
# def rm_small(mylist):
#     return [i for i in mylist if i > min(mylist)]