# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yyIz7LXXYMQVM8M88hNlAdJKl5n3BvKc
"""

def solution(seoul):
    ind = seoul.index("Kim")
    return ('김서방은 {}에 있다').format(ind)

#다른 사람이 푼 것도 비슷함
# def findKim(seoul):
#     return "김서방은 {}에 있다".format(seoul.index('Kim'))