# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(n): #에라토스테네스 체
  num = set(range(2,n+1))

  for i in range(2,int(n**0.5)+1):
    if i in num:
      num-=set(range(2*i,n+1,i))
  return len(num)

print(solution(10))
print(solution(5))

# 루트n 이전까지 솟수의 배수를 제거 했고, 
#남은 수에서 솟수의 배수가 있으려면 루트n이 소소수라면 
#그보다 작은 소소수와의 곱은 이미 제거되었기 때문에 루트n 이후는 제거 필요없음.

#num-=set(range(2*i,n+1,i)) --> num -= set(range(i*i,n+1,i)) 같은 관점에서 이렇게도 수정해도 될 것 같습니다.