# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(s):
  index_num = []
  result = []
  
  for i in range(len(s)):
    if s[i] in s[:i]:
      index_num = []
      for num in range(0,i):
        if s[i] == s[num] and i != num:
          index_num.append(abs(i - num))
      result.append(min(index_num))
    else:
      result.append(-1)

  return result

#print(solution("banana"))
#print(solution("foobar"))
print(solution("baaab")) #[-1, -1, 1, 1, 4]

#다른 사람의 풀이1..
def solution(s):
    answer = []
    dic = dict()
    for i in range(len(s)):
        if s[i] not in dic:
            answer.append(-1)
        else:
            answer.append(i - dic[s[i]])
        dic[s[i]] = i

    return answer

#다른 사람의 풀이2...
def solution(s):
    answer = []
    alphas = {}
    for i in range(len(s)):
        if s[i] in alphas:
            answer.append(i - alphas[s[i]])
        else:
            answer.append(-1)
        alphas[s[i]] = i
    return answer