# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yyIz7LXXYMQVM8M88hNlAdJKl5n3BvKc
"""

def solution(phone_number):
    return ('*'*len(phone_number[:-4])+phone_number[-4:])

#다른 사람이 푼 것도 비슷함
# def hide_numbers(s):
#     return "*"*(len(s)-4) + s[-4:]

#정규식 사용...?한 다른 사람 풀이이
# import re

# def hide_numbers(s):
#     p = re.compile(r'\d(?=\d{4})')
#     return p.sub("*", s, count = 0)