# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

from itertools import combinations
def solution(numbers):
  new_nums = []
  for i in list(combinations(numbers, 2)):
    new_nums.append(sum(i))
  return sorted(list(set(new_nums)))

print(solution([2,1,3,4,1]))
print(solution([5,0,2,7])) 

#다른 사람의 풀이1 
def solution(numbers):
    answer = []
    for i in range(len(numbers)):
        for j in range(i+1, len(numbers)):
            answer.append(numbers[i] + numbers[j])
    return sorted(list(set(answer)))

#다른 사람의 풀이2
def solution(numbers): 
  return sorted({numbers[i] + numbers[j] for i in range(len(numbers)) for j in range(len(numbers)) if i>j})