# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(food):
  food_list = []
  for index, value in enumerate(food[1:],start=1):
    food_list.append(str(index)*(value//2)); 
  food_list.append("0")
  food_list.extend(reversed(food_list[:-1]))
  return (''.join(food_list))

print(solution([1, 3, 4, 6])) #1은 물임임
print(solution([1, 7, 1, 2]))

#다른 사람의 풀이1...
def solution(food):
    answer = ''
    for i,n in enumerate(food[1:]):
        answer += str(i+1) * (n//2)
    return answer + "0" + answer[::-1]

#다른 사람의 풀이2...
from itertools import chain

def solution(food):
    stack = []
    for i in range(1, len(food)):
        for _ in range(food[i]//2):
            stack.append(i)
    return "".join(map(str, chain(stack, [0], stack[::-1])))