# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uw0QVP-vQkmMglFJ-X09JEcUjg9BE75F
"""

def solution(numbers):
    sum = 0
    for i in numbers: 
        sum+=i
    return (45-sum)

# def solution(numbers):
#     return 45 - sum(numbers)

# solution = lambda x: sum(range(10)) - sum(x)