# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(cards1, cards2, goal): #삭제하면 인덱스 0으로 해도 됨.
  for target in goal:
        if len(cards1) and target == cards1[0]: 
          cards1.pop(0)
        elif len(cards2) and target == cards2[0]: 
          cards2.pop(0)
        else: 
          return 'No'
  return 'Yes'

print(solution(["i", "drink", "water"],["want", "to"],["i", "want", "to", "drink", "water"]))
print(solution(["i", "water", "drink"],["want", "to"],["i", "want", "to", "drink", "water"]))

# 다른 사람의 풀이1..
def solution(cards1, cards2, goal):
    answer = "Yes"
    a=0
    b=0
    for i in goal:
        if i == cards1[a]:
            a += 1
            a = min(len(cards1)-1,a)
        elif i == cards2[b]:
            b += 1
            b = min(len(cards2)-1,b)
        else:
            answer = "No"
            break  
    return answer

# 다른 사람의 풀이2
from collections import deque

def solution(cards1, cards2, goal):
    card1_q = deque(list(cards1))
    card2_q = deque(list(cards2))

    for target in goal:
        if card1_q and card1_q[0] == target:
            card1_q.popleft()
        elif card2_q and card2_q[0] == target:
            card2_q.popleft()
        else:
            return "No"

    return "Yes"