# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(id_list, report, k):
  report = set(report) #중복 제거
  result = {i:0 for i in id_list}  #메일 보낼 횟수
  reported = {i:0 for i in id_list}  #신고 당한 횟수

  for i in report:
    reported[i.split()[1]] += 1

  for i in report:
    if reported[i.split()[1]] >= k:
      result[i.split()[0]] += 1

  return list(result.values())

print(solution(["muzi", "frodo", "apeach", "neo"],["muzi frodo","apeach frodo","frodo neo","muzi neo","apeach muzi"],2))
print(solution(["con", "ryan"],["ryan con", "ryan con", "ryan con", "ryan con"],3))

#다른 사람의 풀이1..
def solution(id_list, report, k):
    answer = [0] * len(id_list)
    dic_report = {id: [] for id in id_list} # 해당 유저를 신고한 ID
    for i in set(report):
        i = i.split()
        dic_report[i[1]].append(i[0])

    for key, value in dic_report.items():
        if len(value) >= k:
            for j in value:
                answer[id_list.index(j)] += 1

    return answer

#다른 사람의 풀이2..
def solution(id_list, report, k):
    answer = []
    id_dict = {}
    reported = {}
    for i in id_list:
        id_dict[i] = []
        reported[i] = 0

    report_set = list(set(report))
    for i in report_set:
        a, b = i.split()
        id_dict[a].append(b)
        reported[b] += 1

    for key in id_dict:
        temp = 0
        for value in id_dict[key]:
            if reported[value] >= k:
                temp += 1
        answer.append(temp)

    return answer