# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(price, money, count): #걍 등차수열 쓰기,,
  gap = (money -(count*(2*price+(count - 1)*price))/2)
  return (0 if gap >= 0 else abs(gap))

print(solution(3,20,4))
#print(solution())

#다른 사람의 풀이...내가 생각한 걸 한 줄로 더 줄임
# def solution(price, money, count):
#     return max(0,price*(count+1)*count//2-money)

#다른 사람의 풀이2
# def solution(price, money, count):
#     return abs(min(money - sum([price*i for i in range(1,count+1)]),0))

#다른 사람의 풀이3, 가독성 좋음
# def solution(price, money, count):
#     # answer = -1
#     pay = 0
#     for i in range(1, count+1):
#         pay += (price * i)
#     if money < pay:
#         return pay - money
#     else:
#         return 0