# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(s):
    new_s = list(s)
    sum_p = 0
    sum_y = 0
    for i in new_s:
        if(i=='p' or i=='P'):
            sum_p = sum_p+1
            #sum_p++
        elif(i=='y' or i=='Y'):
            sum_y = sum_y+1
            #sum_y++

# def numPY(s):
#     # 함수를 완성하세요
#     return s.lower().count('p') == s.lower().count('y')

# def numPY(s):
#     c = Counter(s.lower())
#     return c['y'] == c['p']