# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

from itertools import combinations
def solution(number):
  num_com = list(combinations(number, 3))
  count = 0
  for i in num_com: 
    if sum(i) == 0:
      count+=1
  return count

print(solution([-2, 3, 0, 2, -5]))
print(solution([-3, -2, -1, 0, 1, 2, 3])) 
print(solution([-1, 1, -1, 1])) 

#다른 사람의 풀이1 -> 거의 동일
def solution (number) :
    from itertools import combinations
    cnt = 0
    for i in combinations(number,3) :
        if sum(i) == 0 :
            cnt += 1
    return cnt

#다른 사람의 풀이2 -> 거의 동일
from itertools import combinations
def solution(number):
    return sum([1 for c in list(combinations(number,3)) if not sum(c)])