# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(n):
    if((n**(1/2)).is_integer()==True): #제곱근이 정수이면 
        return ((n**(1/2)+1)**2)
    else:
        return -1

# def nextSqure(n):
#     sqrt = n ** (1/2)

#     if sqrt % 1 == 0:
#         return (sqrt + 1) ** 2
#     return 'no'

# def nextSqure(n):
#     return n == int(n**.5)**2 and int(n**.5+1)**2 or 'no'