# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(X, Y): 
  #어쩔 수 없이 형변환 다 포기하고 참고함.. 
  # 이중 for문, 형 변환이 생각보다 시간 많이 잡아먹음.
    answer = ''

    for i in range(9,-1,-1) :
        answer += (str(i) * min(X.count(str(i)), Y.count(str(i))))

    if answer == '' :
        return '-1'
    elif len(answer) == answer.count('0'):
        return '0'
    else :
        return answer

print(solution("100","2345"))
print(solution("100","203045"))
print(solution("100","123450"))
print(solution("12321","42531"))
print(solution("5525","1255"))

#실패한 (시간초과) 코드들.
def solution(X, Y): #시간 초과...
  from itertools import permutations
  X = list(map(int,X)); Y = list(map(int,Y)); 
  X_dict = {}; Y_dict = {}; result = []
  
  for i in set(X):
    X_dict[i] = X.count(i)

  for i in set(Y):
    Y_dict[i] = Y.count(i)

  for xele,xval in X_dict.items():
    for yele,yval in Y_dict.items():
      if (xele == yele):
        result.append(str(xele)*min(xval,yval))

  if len(result)==0:
    result.append('-1') 
  else:
    result = list(''.join(result))     
    result = list(permutations(result, len(result)))
    result = list(map(int,[''.join(i) for i in result]))
    
  return str(max(result))


#실패한 코드2..
def solution(X, Y): #아무리 봐도 이게 시간초과면 형 변환 못할 듯...ㅎ.. 
  #int 안 쓰려면 0만 고려하면 됨
  result = []
  
  for i in range(9,-1,-1): #걍 처음부터 내림차순으로 해보기
    result.append(str(i)* min(X.count(str(i)),Y.count(str(i))))
  
  result = [i for i in result if (i != '')]

  if len(result) == 0:
    return '-1'
  else:
    result = ''.join(result)

  return  result

#다른 사람의 코드2..너무 복잡함..
from functools import reduce
import re
def solution(X, Y):
    result = "".join(sorted(reduce(lambda result, i: result + i*min(X.count(i), Y.count(i)), map(str, range(10)), ""), reverse=True)) or "-1"
    return "0" if re.match(r"0+", result) else result

#다른 사람의 코드3...
def solution(X, Y):
    xList = list(X.count(str(x)) for x in range(10))
    yList = list(Y.count(str(y)) for y in range(10))
    answer = ""
    for i in range(9, -1, -1):
        answer += str(i) * min(xList[i], yList[i])

    if answer == "":
        return "-1"
    elif answer[0] == "0" and answer[len(answer) - 1] == "0": #내가 잘 고려 못했던 코드.
        return "0"
    else:
        return answer