# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(num):
    if num%2==0:
        return "Even"
    else:
        return "Odd"

print(solution(3))
print(solution(4))