# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(n):
    n_list = list(map(str, str(n))) 
    sort_list = sorted(n_list,reverse=True)
    result = ''.join(sort_list)
    return int(result)

print(solution(118372))

#비슷함
# def solution(n):
#     ls = list(str(n))
#     ls.sort(reverse = True)
#     return int("".join(ls))