# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WM3VWkTr_hdUuxpAYUwcp_Fq_E_fh4uY
"""

def solution(arr, divisor):
    new_arr= sorted([i for i in arr if(i%divisor==0)])
    return ([-1] if (len(new_arr)==0) else new_arr)

print(solution([5, 9, 7, 10],5))
print(solution([2, 36, 1, 3],1))
print(solution([3,2,6],10))

#다른 사람 풀이 -> 나의 코드 간소화화
#def solution(arr, divisor): 
#  return sorted([n for n in arr if n%divisor == 0]) or [-1]