# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(n):
    sum = 0.0
    for i in range(1,n+1):
        if n%i==0:
            sum += i
        else:
            continue
    return sum
#return num + sum([i for i in range(1, (num // 2) + 1) if num % i == 0])