# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

def solution(s):    
    return(s[int(len(s)/2)-1:int(len(s)/2)+1] if(len(s)%2==0) else s[int(len(s)/2)])

print(solution("abcde"))
print(solution("qwer"))

#다른 사람 풀이
# def string_middle(str):
#     return str[(len(str)-1)//2:len(str)//2+1]