# -*- coding: utf-8 -*-
"""연습용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cI7vkqxs5WMh_9o0NpCARdKUabvS0EOe
"""

import math 
def solution(dartResult): #진심 환장하겠네 걍 무식하게 푼다...
  answer = []
  for i in range(len(dartResult)):
    if dartResult[i] == 'S' or dartResult[i] == 'D' or dartResult[i] == 'T':
      if dartResult[i] == 'S':
        if dartResult[i-2:i].isdecimal():
          answer.append(int(dartResult[i-2:i]))
        else:
          answer.append(int(dartResult[i-1]))
      elif dartResult[i] == 'D':
        if dartResult[i-2:i].isdecimal():
          answer.append(math.pow(int(dartResult[i-2:i]),2))
        else:
          answer.append(math.pow(int(dartResult[i-1]),2))
      elif dartResult[i] == 'T':
        if dartResult[i-2:i].isdecimal():
          answer.append(math.pow(int(dartResult[i-2:i]),3))
        else:
          answer.append(math.pow(int(dartResult[i-1]),3))

  bonus_count = 0
  for i in range(len(dartResult)):
    bonus_count = dartResult[:i].count('S') + dartResult[:i].count('D') + dartResult[:i].count('T')
    if dartResult[i] == '*': #해당 점수와 바로 전에 얻은 점수 각각 2배.
      if bonus_count == 1:
        answer[0] *= 2
        
      elif bonus_count == 2:
        answer[0] *= 2
        answer[1] *= 2

      elif bonus_count == 3:
        answer[1] *= 2
        answer[2] *= 2

    elif dartResult[i] == '#': #해당 점수만 마이너스.
      if bonus_count == 1:
        answer[0] *= -1
        
      elif bonus_count == 2:
        answer[1] *= -1

      elif bonus_count == 3:
        answer[2] *= -1
 
  return int(sum(answer))       

print(solution("1S2D*3T"))
print(solution("1D2S#10S"))
print(solution("1D2S0T"))
print(solution("1S*2T*3S"))
print(solution("1D#2S*3S"))
print(solution("1T2D3D#"))
print(solution("1D2S3T*"))

#다른 사람의 풀이1..화나네..re.compile에 대해서 알아가기.
import re


def solution(dartResult):
    bonus = {'S' : 1, 'D' : 2, 'T' : 3}
    option = {'' : 1, '*' : 2, '#' : -1}
    p = re.compile('(\d+)([SDT])([*#]?)')
    dart = p.findall(dartResult)
    for i in range(len(dart)):
        if dart[i][2] == '*' and i > 0:
            dart[i-1] *= 2
        dart[i] = int(dart[i][0]) ** bonus[dart[i][1]] * option[dart[i][2]]

    answer = sum(dart)
    return answer

#다른 사람의 풀이2...K로 처리하는 거 배워갑니당.
def solution(dartResult):
    point = []
    answer = []
    dartResult = dartResult.replace('10','k')
    point = ['10' if i == 'k' else i for i in dartResult]
    print(point)

    i = -1
    sdt = ['S', 'D', 'T']
    for j in point:
        if j in sdt :
            answer[i] = answer[i] ** (sdt.index(j)+1) #오우.
        elif j == '*':
            answer[i] = answer[i] * 2
            if i != 0 :
                answer[i - 1] = answer[i - 1] * 2
        elif j == '#':
            answer[i] = answer[i] * (-1)
        else:
            answer.append(int(j))
            i += 1
    return sum(answer)

#다른 사람의 풀이3...
def solution(dartResult):
    dart = {'S':1, 'D':2, 'T':3}
    scores = []
    n = 0

    for i, d in enumerate(dartResult):
        if d in dart:
            scores.append(int(dartResult[n:i])**dart[d]) #아하.
        if d == "*":
            scores[-2:] = [x*2 for x in scores[-2:]]
        if d == "#":
            scores[-1] = (-1)*scores[-1]
        if not (d.isnumeric()):
            n = i+1

    return sum(scores)