# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c75-Cr0TfQuGgHxqaIJ0bE00EscZMsOS
"""

def solution(n):
    n_list = list(map(int, str(n))) 
    n_list.reverse()
    return n_list

# def digit_reverse(n):
#     return list(map(int, reversed(str(n))))